INSERT INTO AUTHOR (AUTHOR_ID,NAME,MIDDLENAME,SURNAME) VALUES (1,'Михаил','Афанасьевич','Булгаков');
INSERT INTO AUTHOR (AUTHOR_ID,NAME,MIDDLENAME,SURNAME) VALUES (2,'Лев','Николаевич','Толстой');
INSERT INTO AUTHOR (AUTHOR_ID,NAME,MIDDLENAME,SURNAME) VALUES (3,'Федор','Михайлович','Достоевский');
INSERT INTO AUTHOR (AUTHOR_ID,NAME,MIDDLENAME,SURNAME) VALUES (4,'Александр','Сергеевич','Пушкин');
INSERT INTO AUTHOR (AUTHOR_ID,NAME,MIDDLENAME,SURNAME) VALUES (5,'Михаил','Юрьевич','Лермонтов');