INSERT INTO GENRE (GENRE_ID,TITLE) VALUES (1,'Роман');
INSERT INTO GENRE (GENRE_ID,TITLE) VALUES (2,'Повесть');
INSERT INTO GENRE (GENRE_ID,TITLE) VALUES (3,'Рассказ');
INSERT INTO GENRE (GENRE_ID,TITLE) VALUES (4,'Стихотворение');
INSERT INTO GENRE (GENRE_ID,TITLE) VALUES (5,'Поэма');