INSERT INTO BOOK (BOOK_ID,TITLE,AUTHOR_ID,GENRE_ID,PUBLISHER,YEAR,CITY) VALUES (1,'Мастер и Маргарита',1,1,'Москва','1920','Москва');
INSERT INTO BOOK (BOOK_ID,TITLE,AUTHOR_ID,GENRE_ID,PUBLISHER,YEAR,CITY) VALUES (2,'Война и мир',2,1,'Питер','1918','Питер');
INSERT INTO BOOK (BOOK_ID,TITLE,AUTHOR_ID,GENRE_ID,PUBLISHER,YEAR,CITY) VALUES (3,'Преступление и наказание',3,1,'O’Reilly','1866','Москва');
INSERT INTO BOOK (BOOK_ID,TITLE,AUTHOR_ID,GENRE_ID,PUBLISHER,YEAR,CITY) VALUES (4,'Медный всадник',4,5,'Питер','1821','Питер');
INSERT INTO BOOK (BOOK_ID,TITLE,AUTHOR_ID,GENRE_ID,PUBLISHER,YEAR,CITY) VALUES (5,'Мастер и Маргарита',5,4,'O’Reilly','1852','Питер');